<section class='section' role='main'><div class='content ptb8'><div class='legal-doc center'><div class='col span2of3 mid-span1of1 normalize align-left'><p>Thanks for using <?php echo $_SESSION['projectname']; ?>.</p>

<p>Please read these Terms carefully. By using <?php echo $_SESSION['projectname']; ?> or signing up for an account, you’re agreeing to these Terms. This is a legal agreement.
We’ll start with the basics, including a few definitions that should help you understand this agreement. <?php echo $_SESSION['projectname']; ?> (“<?php echo $_SESSION['projectname']; ?>” or the “Service”) is an email service offered through the URL <a href='<?php echo $_SESSION['projectweb']; ?>'><?php echo $_SESSION['projectweb']; ?></a> (we’ll refer to it as the “Website”) that allows you to create, send, and manage email newsletters (each message is called an “Email”) to individual recipients. <?php echo $_SESSION['projectname']; ?> is owned and operated by The Rocket Science Group, LLC d/b/a <?php echo $_SESSION['projectname']; ?>, a Georgia limited liability corporation (“<?php echo $_SESSION['projectname']; ?>,” “we,” or “us”). <?php echo $_SESSION['projectname']; ?> has employees, independent contractors, and representatives (“our Team”). As a customer of the Service or a representative of an entity that’s a customer of the Service, you’re a “Member” according to this agreement (or “you”).</p>

<p>These Terms of Use (“Terms,” including our <a href='http://<?php echo $_SESSION['projectname']; ?>.com/legal/privacy'>Privacy Policy</a>, <a href='http://<?php echo $_SESSION['projectname']; ?>.com/legal/acceptable_use'>Acceptable Use Policy</a>, <a href='http://<?php echo $_SESSION['projectname']; ?>.com/legal/api_use'>API Guidelines</a>, <a href='http://<?php echo $_SESSION['projectname']; ?>.com/legal/copyright/'>Copyright Policy</a> and <a href='http://<?php echo $_SESSION['projectname']; ?>.com/about/brand-assets'>Brand Guidelines</a>) define the terms and conditions under which you’re allowed to use <?php echo $_SESSION['projectname']; ?>, and how we’ll treat your account while you’re a Member. If you have any questions about our terms, feel free to <a href='http://<?php echo $_SESSION['projectname']; ?>.com/contact'>contact us</a>.</p>
<h1 id='section-account'>ACCOUNT</h1><h2>1. Eligibility</h2>
<p>In order to use <?php echo $_SESSION['projectname']; ?>, you must:</p>
<ol class='list markers'><li>be at least eighteen (18) years old and able to enter into contracts;</li><li>complete the registration process;</li><li>agree to the Terms; and</li><li>provide true, complete, and up to date contact information.</li></ol>
<p>By using <?php echo $_SESSION['projectname']; ?>, you represent and warrant that you meet all the requirements listed above, and that you won’t use <?php echo $_SESSION['projectname']; ?> in a way that violates any laws or regulations. (Representing and warranting is like making a legally enforceable promise.) <?php echo $_SESSION['projectname']; ?> may refuse service, close accounts of any users, and change eligibility requirements at any time.</p>
<h2>2. Term</h2>
<p>The Term begins when you sign up for <?php echo $_SESSION['projectname']; ?> and continues as long as you use the Service. Clicking the button and entering your username means that you’ve officially “signed” the Terms. If you sign up for <?php echo $_SESSION['projectname']; ?> on behalf of a company or other entity, you represent and warrant that you have the authority to accept these Terms on their behalf.</p>
<h2>3. Closing Your Account</h2>
<p>You or <?php echo $_SESSION['projectname']; ?> may terminate this Agreement at any time and for any reason by giving Notice to the other party. We may suspend our Service to you at any time, with or without cause. If we terminate your account without cause, we’ll refund a prorated portion of your monthly prepayment or reimburse you for unused <a href='http://<?php echo $_SESSION['projectname']; ?>.com/pricing'>Email Credits</a>. We won’t refund or reimburse you if there’s cause, like a violation of these Terms or our Acceptable Use Policy. Once terminated, we may permanently delete your account and all the data associated with it, including your emails from our Website. If you don’t log in to your account for 12 or more months, we may treat your account as “inactive” and permanently delete the account and all the data associated with it.</p>
<h2>4. Changes</h2>
<p>We may change any of the Terms by posting revised Terms of Use on our Website and/or by sending an email to the last email address you gave us. Unless you terminate your account within ten (10) days, the new Terms will be effective immediately and apply to any continued or new use of <?php echo $_SESSION['projectname']; ?>. We may change the Website, the Service, or any features of the Service at any time.</p>
<h2>5. Account and Password</h2>
<p>You’re responsible for keeping your account name and password confidential. You’re also responsible for any account that you have access to, whether or not you authorized the use. You’ll immediately notify us of any unauthorized use of your accounts. We’re not responsible for any losses due to stolen or hacked passwords. We don’t have access to your current password, and for security reasons, we may only reset your password.</p>
<h2>6. Account Disputes</h2>
<p>We don’t know the inner workings of your organization or the nature of your personal relationships, and we don’t arbitrate disputes over who owns an account. You won’t request access to or information about an account that’s not yours, and you’ll resolve any account-related disputes directly with the other party. We decide who owns an account based on the content of the emails in that account, and if multiple people or entities are identified in the content, then we’ll rely on the contact information listed for that account.</p>
<h1 id='section-payment'>PAYMENT</h1><h2>7. Monthly Plans</h2>
<p>Our charges for monthly plans are <a href='http://<?php echo $_SESSION['projectname']; ?>.com/pricing'>posted</a> on our Website and may be changed from time to time. If any part of a month is included in the Term, then payment is due for the full month. Payments are due for any month on the same or closest date to the day you made your first monthly payment (the “Pay Date”). If you go over your sending limit and reach another pricing level, then you’ll have to pay at the higher level on or before the next pay date. If the Term ends before that payment is due, you’ll still be required to make one payment at the higher level.</p>
<h2>8. Pay as You Go Plans</h2>
<p>You may buy Email Credits to use our Services instead of signing up for a monthly plan. This is explained on the <a href='http://<?php echo $_SESSION['projectname']; ?>.com/pricing'>pricing page</a> of our Website. If you choose a Pay as You Go Plan, you’ll still be considered a Member, and other than the monthly payment requirement, all the terms of this Agreement will still apply to you. Email Credits for Pay as You Go accounts roll over and don’t expire, but if your account is inactive for more than 12 months, it may be deleted.</p>
<h2>9. Credit Cards</h2>
<p>As long as you’re a Member or have an outstanding balance with us, you’ll provide us with valid credit card information and authorize us to deduct the monthly charges against that credit card. You’ll replace the information for any credit card that expires with information for a valid one. Anyone using a credit card represents and warrants that they are authorized to use that credit card, and that any and all charges may be billed to that credit card and won’t be rejected. If we’re unable to process your credit card order, we’ll try to contact you by email and suspend your account until your payment can be processed.</p>
<h2>10. Refunds</h2>
<p>We’ll give you a refund for a prepaid month if we stop providing our Services to you for a reason that’s not laid out in these Terms or our <a href='http://<?php echo $_SESSION['projectname']; ?>.com/legal/acceptable_use'>Acceptable Use Policy</a>. You won’t be entitled to a refund from us under any other circumstances. We may offer a refund if a Member applies for one based on the requirements posted on the Website.</p>
<h2>11. Charges for Add-Ons</h2>
<p>Some features are offered as add-ons to your <?php echo $_SESSION['projectname']; ?> account. If you add on a feature that has a charge, then you’ll be billed that additional amount with each billing cycle for as long as the add-on is active. Some add-ons, like Mandrill, are intended for particular use cases and may have additional terms or restrictions (“Additional Terms.”) If you use an add-on in a way that violates these Terms or the Additional Terms, then we may terminate your account. If you use Mandrill to send bulk emails, in violation of our Acceptable Use Policy, then we may charge you at the comparable <?php echo $_SESSION['projectname']; ?> pricing tier or terminate your account.</p>
<h2>12. Billing Changes</h2>
<p>We may change our fees at any time by posting a new pricing structure to our Website and/or sending you a notification by email.</p>
<h1 id='section-rights'>RIGHTS</h1><h2>13. Proprietary Rights Owned by Us</h2>
<p>You will respect our proprietary rights in the Website and the software used to provide <?php echo $_SESSION['projectname']; ?> (proprietary rights include patents, trademarks, service marks, trade secrets, and copyrights). You may only use our brand assets according to our <a href='http://<?php echo $_SESSION['projectname']; ?>.com/about/brand-assets/'>Brand Guidelines</a>.</p>
<h2>14. Proprietary Rights Owned by You</h2>
<p>You represent and warrant that you either own or have permission to use all of the material in your Emails. You retain ownership of the materials that you upload to the Service. We may use or disclose your materials only as described in these Terms and our Privacy Policy.</p>
<h2>15. Privacy Policy</h2>
<p>We may use and disclose your information according to our <a href='http://<?php echo $_SESSION['projectname']; ?>.com/legal/privacy'>Privacy Policy</a>. Our Privacy Policy will be treated as part of these Terms.</p>
<h2>16. Right to Review Email Campaigns</h2>
<p>We may view, copy, and internally distribute content from your Emails and account to create algorithms and programs (“Tools”) that help us spot problem accounts. We use these Tools to find Members who violate these Terms or laws. For example, We study data internally to make our Email Genome Project smarter and create better experiences for senders and subscribers.</p>
<h1 id='section-rules-and-abuse'>RULES AND ABUSE</h1><h2>17. General Rules</h2>
<p>You promise to follow these rules:</p>
<ol class='list markers'><li>You won’t send Spam! By “spam,” we mean the definition on the <a href='http://www.spamhaus.org/definition.html'>Spamhaus website</a>.</li><li>You won’t use purchased, rented, or third-party lists of email addresses.</li><li>You won’t violate our Acceptable Use Policy, which is part of this Agreement.</li><li>If you use our API, you’ll comply with our <a href='http://<?php echo $_SESSION['projectname']; ?>.com/legal/api_use'>API Use Policy</a>.</li></ol>
<p>If you violate any of these rules, then we may suspend or terminate your account.</p>
<h2>18. Reporting Abuse</h2>
<p>If you think anyone is violating any of these Terms, please notify us immediately. If you received spam you think came from a <?php echo $_SESSION['projectname']; ?> user, please report it to our <a href='http://<?php echo $_SESSION['projectname']; ?>.com/contact/abuse/'>abuse team</a>. (The best way to tell whether an email was sent through <?php echo $_SESSION['projectname']; ?> is that every <?php echo $_SESSION['projectname']; ?> campaign has an embedded Campaign Tracking ID in the header that makes it easy to report suspected spam.) If you think anyone has posted material that violates any copyrights, then you can notify us according to our <a href='http://<?php echo $_SESSION['projectname']; ?>.com/legal/copyright/'>Copyright Policy</a>.</p>
<h2>19. Bandwidth Abuse/Throttling</h2>
<p>You may only use our bandwidth for your <?php echo $_SESSION['projectname']; ?> emails. We provide image and data hosting only for your email campaigns, so you may not host images on our servers for anything else (like a website). We may throttle your sending or connection through our API at our discretion.</p>
<h2>20. Compliance with Laws</h2>
<p>You represent and warrant that your use of <?php echo $_SESSION['projectname']; ?> will comply with all applicable laws and regulations. You’re responsible for determining whether our Services are suitable for you to use in light of any regulations like HIPAA, GLB, EU Data Privacy Laws, or other laws. If you’re subject to regulations (like HIPAA) and you use our Service, then we won’t be liable if our Service doesn’t meet those requirements. You may not use our Service for any unlawful or discriminatory activities, including acts prohibited by the <a href='https://www.ftc.gov/enforcement/statutes/federal-trade-commission-act'>Federal Trade Commission Act</a>, <a href='https://www.ftc.gov/enforcement/rules/rulemaking-regulatory-reform-proceedings/fair-credit-reporting-act'>Fair Credit Reporting Act</a>, <a href='https://en.wikipedia.org/wiki/Equal_Credit_Opportunity_Act'>Equal Credit Opportunity Act</a>, or other laws that apply to commerce.</p>

<p>If you’re located in the European Economic Area (EEA) or send to anyone in the EEA, you represent and warrant that in creating your Email distribution list, sending Emails via <?php echo $_SESSION['projectname']; ?>, and collecting information as a result of sending Emails, you:</p>
<ol class='list markers'><li>Will clearly describe in writing how you plan to use any data collected, including for your use of <?php echo $_SESSION['projectname']; ?>. You’ll get express consent to transfer data to <?php echo $_SESSION['projectname']; ?> and be processed, and you’ll otherwise comply with whatever privacy policy you have posted.</li><li>Have complied, and will comply, with all regulations, as well as data protection, electronic communication, and privacy laws that apply to the countries where you’re sending any form of email through <?php echo $_SESSION['projectname']; ?>.</li><li>Have collected, stored, used, and transferred all data relating to any individual in compliance with all data protection laws and regulations. You have the necessary permission to allow <?php echo $_SESSION['projectname']; ?> to receive and process data and send communications to that individual on your behalf.</li><li>Agree to indemnify and hold us harmless from any losses, including attorney fees, that result from your breach of any part of these warranties.</li><li>Have signed our <a href='http://<?php echo $_SESSION['projectname']; ?>.com/legal/forms/data-processing-agreement/'>Data Processing Agreement</a>.</li></ol><h2>21. U.S. Export Controls</h2>
<p>The software that supports the Services (the “Software”) is subject to United States export controls. Export laws are set up by the government to keep certain goods and services from reaching other countries, usually because of security concerns or trade agreements. None of the Software may be downloaded or otherwise exported or re-exported in violation of United States export laws. You’re downloading and using the Software at your own risk.</p>
<h1 id='section-liability'>LIABILITY</h1><h2>22. Limitation of Liability</h2>
<p><strong>To the maximum extent permitted by law, you assume full responsibility for any loss that results from your use of the Website and the Services, including any downloads from the Website. We and our Team won’t be liable for any indirect, punitive, special, or consequential damages under any circumstances, even if they’re based on negligence or we’ve been advised of the possibility of those damages. Our total liability for all claims made about the Service in any month will be no more than what you paid us for the Service the month before.</strong></p>
<h2>23. No Warranties</h2>
<p><strong>To the maximum extent permitted by law, we provide the material on the Website and the Service as is. That means we don’t provide warranties of any kind, either express or implied, including but not limited to warranties of merchantability and fitness for a particular purpose. Since people use <?php echo $_SESSION['projectname']; ?> for a variety of reasons, we can’t guarantee that it will meet your specific needs.</strong></p>
<h2>24. Indemnity</h2>
<p>You agree to indemnify and hold us and our Team harmless from any losses, including attorney fees that result from any claims you make that aren’t allowed under these Terms due to a “Limitation of Liability” or other provision. (Indemnity is an agreement to compensate someone for a loss.) You also agree to indemnify and hold us harmless from any losses, including attorney fees, that result from third-party claims that you or someone using your password did something that, if true, would violate any of these Terms.</p>
<h2>25. Attorney Fees</h2>
<p>If we file an action against you claiming you breached these Terms and we prevail, we’re entitled to recover reasonable attorney fees and any damages or other relief we may be awarded.</p>
<h2>26. Equitable Relief</h2>
<p>If you violate these Terms then we may seek injunctive relief (meaning we may request a court order to stop you) or other equitable relief.</p>
<h2>27. Subpoena Fees</h2>
<p>If we have to provide information in response to a subpoena related to your account, then we may charge you for our costs. These fees may include attorney and employee time spent retrieving the records, preparing documents, and participating in a deposition.</p>
<h2>28. Disclaimers</h2>
<p>We and our Team aren’t responsible for the behavior of any advertisers, linked websites, or other Members.</p>
<h1 id='section-fine-print'>FINE PRINT</h1><h2>29. Notice to U.S. Government End Users</h2>
<p>The Software and Website, including all documentation, are “Commercial Items,” as that term is defined at 48 C.F.R. §2.101, and consist of “Commercial Computer Software” and “Commercial Computer Software Documentation.” The Commercial Computer Software and Commercial Computer Software Documentation are licensed to U.S. Government end users:</p>
<ol class='list markers'><li>only as Commercial Items,</li><li>with the same rights as all other end users, and</li><li>according to the Terms</li></ol>
<p>Published and Unpublished rights are reserved under the copyright laws of the United States. Manufacturer is The Rocket Science Group, LLC, 675 Ponce de Leon Ave NE, Suite 5000, Atlanta, Georgia 30308.</p>
<h2>30. Assignments</h2>
<p>You may not assign any of your rights under this agreement to anyone else. We may assign our rights to any other individual or entity at our discretion.</p>
<h2>31. Choice of Law</h2>
<p>The State of Georgia’s laws, except for conflict of laws rules, will apply to any dispute related to these Terms or the Service. Any dispute related to the Terms, the Privacy Policy, or the Service itself will be decided by the state and federal courts in Fulton County, Georgia, and each party will be subject to the jurisdiction of those courts.</p>
<h2>32. Force Majeure</h2>
<p>We won’t be held liable for any delays or failure in performance of any part of the Service, from any cause beyond our control. This includes, but is not limited to, acts of God, changes to law or regulations, embargoes, war, terrorist acts, riots, fires, earthquakes, nuclear accidents, zombie apocalypse, floods, strikes, power blackouts, volcanic action, unusually severe weather conditions, and acts of hackers or third-party internet service providers.</p>
<h2>33. Survivability</h2>
<p>Even if this Agreement is terminated, the following sections will continue to apply: Proprietary Rights Owned by Us, Proprietary Rights Owned by You, Compliance with Laws, Limitation of Liability, No Warranties, Indemnity, Choice of Law, Severability, and Entire Agreement.</p>
<h2>34. Severability</h2>
<p>If it turns out that a section of this Agreement isn’t enforceable, then that section will be removed or edited as little as necessary, and the rest of the Terms will still be valid.</p>
<h2>35. Interpretation</h2>
<p>The headers and sidebar text are provided only to make this agreement easier to read and understand. The fact that we wrote these Terms won’t affect the way this Agreement is interpreted.</p>
<h2>36. Amendments and Waiver</h2>
<p>Amendments or changes to these Terms won’t be effective until we post revised Terms on the Website. If we don’t immediately take action on a violation of these Terms, we’re not giving up any rights under the Terms, and we may still take action at some point.</p>
<h2>37. No Changes in Terms at Request of Member</h2>
<p>Because we have so many Members, we can’t change these Terms for any one Member or group.</p>
<h2>38. Further Actions</h2>
<p>You’ll provide all documents and take any actions necessary to meet your obligations under these Terms.</p>
<h2>39. Notification of Security Breach</h2>
<p>In the event of a security breach that may affect you or anyone on your Email distribution lists (each a “List”), we’ll notify you of the breach and provide a description of what happened. If we determine, and notify you, that you need to forward all or part of that information to anyone on your Lists, you’ll promptly do so.</p>
<h2>40. Notices</h2>
<p>Any notice to you will be effective when we send it to the last email or physical address you gave us or posted on our Website. Any notice to us will be effective when delivered to us along with a copy to our legal counsel: Attn. Legal Department, <?php echo $_SESSION['projectname']; ?>, 675 Ponce de Leon Ave NE, Suite 5000, Atlanta, GA, 30308, or any addresses as we may later post on the Website.</p>
<h2>41. Entire Agreement</h2>
<p>These Terms, our Privacy Policy, Acceptable Use Policy, API Guidelines (all of which are incorporated into these Terms by reference), and any additional terms you’ve agreed to by turning on specific features (“Additional Terms”) make up the entire agreement and supersede all prior agreements, representations, and understandings. Any Additional Terms will be considered incorporated into these Terms when you activate the feature.</p>

<p>Where there’s a conflict between these Terms and the Additional Terms, the Additional Terms will control.</p>

<p>Congratulations! You’ve reached the end. Thanks for taking the time to learn about <?php echo $_SESSION['projectname']; ?>’s policies.</p>
</div></div></div></section>